### ISSUE TITLE
Support executing raw SQL queries

### ISSUE THREAD

**Issue by zhibor** [eakmanrq/sqlframe#149]
There are situations where executing arbitrary SQL queries directly is necessary. For example, some queries might be too complex to be easily expressed using the existing API. Therefore, it would be nice to support raw SQL execution within sqlframe.

**Comment by eakmanrq** [comment]
Hey @zhibor! This is actually supported today since this is supported in the PySpark DataFrame API. What you are looking for is the `sql` method of the session object. Example:

```
from sqlframe.duckdb import DuckDBSession
session = DuckDBSession()
session.sql("SELECT 1").show()
```

You will see an output of `1`. Two things to note when using this approach:
* The default SQL dialect is expected to be Spark. To change, you can set `sqlframe.input.dialect`. See here for more details: https://sqlframe.readthedocs.io/en/stable/configuration/#input-and-output-dialect
* SQLFrame has specific overrides for some more complex functions that won't be applied when using this approach. Therefore it is recommended to use the PySpark API to build the expression directly but this approach can work fine in many cases.

Let me know if this addresses your question!
