### ISSUE TITLE
feature request: addition of pyspark.SparkConf

### ISSUE THREAD

**Issue by sherlockbeard** [eakmanrq/sqlframe#167]
Currently config can be set only at SparkSession Building time .
using 
`builder = SparkSession.builder.appName("MyApp").config("spark.driver.memory", "15g")`

But it look for specific keys 

https://github.com/eakmanrq/sqlframe/blob/13f1c11c283583303535a67db583618ab3d0cde3/sqlframe/base/session.py#L615-L645

maybe we can keep the config in simple dict ?.

and have them `spark.conf.get | spark.conf.set` working 

related to this when we have conf we can pass creds to duckdb 

```spark.conf.set("fs.azure.account.auth.type.<storage-account>.dfs.core.windows.net", "OAuth")
spark.conf.set("fs.azure.account.oauth.provider.type.<storage-account>.dfs.core.windows.net", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id.<storage-account>.dfs.core.windows.net", "<application-id>")
spark.conf.set("fs.azure.account.oauth2.client.secret.<storage-account>.dfs.core.windows.net", service_credential)
spark.conf.set("fs.azure.account.oauth2.client.endpoint.<storage-account>.dfs.core.windows.net", "https://login.microsoftonline.com/<directory-id>/oauth2/token")
```

- [x] Yes. I would be willing to contribute this feature with guidance from the maintainers.

**Comment by eakmanrq** [comment]
Hey @sherlockbeard thanks for the suggestion.

Some context as to why SQLFrame is written this way currently is that is needs to know which of the config is relevant to it and which can be discarded. For example we wouldn't want to pass `spark.driver.memory` kwarg to the construction of a duckdb connection right? That is why SQLFrame checks what config is passed in, stores the values relevant to it, and then discards the rest. Do you have thoughts on how to address this if we start passing all config into the connection constructor? 

One idea would be to just discard `spark.*` config but I don't think it is safe to assume that anything `spark.*` can be passed into the connection.

Another way to solve this problem is to construct the DuckDB connection outside of SQLFrame and then pass that in. For example:
```
import duckdb
from adlfs.spec import AzureBlobFileSystem
from sqlframe.duckdb import DuckDBSession

connection = duckdb.connect()
connection.register_filesystem(AzureBlobFileSystem(account_name='<storage_account>', connection_string='<storage_account_key>'))
session = DuckDBSession(conn=connection)

...
```

Let me know what you think.

**Comment by sherlockbeard** [comment]
> Another way to solve this problem is to construct the DuckDB connection outside of SQLFrame and then pass that in. For example:

this option is good . 

I was thinking if we can dynamically pass specific config

```
spark.conf.set("fs.azure.account.oauth.provider.type.<storage-account>.dfs.core.windows.net", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id.<storage-account>.dfs.core.windows.net", "<application-id>")
spark.conf.set("fs.azure.account.oauth2.client.secret.<storage-account>.dfs.core.windows.net", service_credential)
spark.conf.set("fs.azure.account.oauth2.client.endpoint.<storage-account>.dfs.core.windows.net", "https://login.microsoftonline.com/<directory-id>/oauth2/token")
```

to duckdb SECRET

query = connection.sql(f'''
CREATE SECRET tf12test (TYPE AZURE, CONNECTION_STRING '${Azure_key}', ACCOUNT_NAME 'tf12test');
''')

But now I realize it will be too much work without much meaning 😴.
