### ISSUE TITLE
very poor support for TPCDS

### ISSUE THREAD

**Issue by djouallah** [eakmanrq/sqlframe#173]
it seems to be a bug, sqlframe don't seems to support tpcds queries at all, is this a sqlglot issue ?

https://colab.research.google.com/drive/1NGFqooYmbKs2ffQkTzMu_AWTHCHbE419#scrollTo=bANKQEwPhETg

so far only 5 % of the queries did run

**Comment by eakmanrq** [comment]
Thanks for sharing this. I'm going to add this to the SQLFrame test suite and fix any issues. In general the best compatibility in SQLFrame will be using DataFrame operations directly (not passing in SQL) but it should perform much better on these queries. This should only matter when using more advanced functions since SQLFrame has specific overrides to maintain PySpark compatibility that are not part of SQLGlot. 

One workaround while I improve this is to change `engine.sql(value).show()` to `engine.sql(value, qualify=False).show()` for SQLFrame. That will fix many of them but that shouldn't be needed and some others still have issues which I will take a look.

**Comment by eakmanrq** [comment]
Fixed in `3.3.0`. The `qualify=False` workaround is no longer needed.

@djouallah Let me know if you notice any performance concerns in this latest release. To fix the issue I used an approach that was most simple/versatile but could have unexpected performance implications. If you notice then I can find something more performant for each format.

**Comment by djouallah** [comment]
it is way better, the performance is a bit strange , duckdb finish the test under 8 seconds

<img width="358" alt="image" src="https://github.com/user-attachments/assets/9d1fadb7-741d-4a9d-abd1-29bf25aa3341">

**Comment by eakmanrq** [comment]
> it is way better, the performance is a bit strange , duckdb finish the test under 8 seconds
> 
> 
> 
> <img width="358" alt="image" src="https://github.com/user-attachments/assets/9d1fadb7-741d-4a9d-abd1-29bf25aa3341">
> 
> 

Do you happen to know how long DuckDB alone takes? That would be a good baseline to compare against.

**Comment by djouallah** [comment]
yes, duckdb alone took 8 second using version 1.1

**Comment by eakmanrq** [comment]
> yes, duckdb alone took 8 second using version 1.1 

Ok thanks I will take a look at this next.

**Comment by djouallah** [comment]
i added back duckdb, the joy of sql, I fixed the space name for spark which duckdb does not like :)  
<img width="374" alt="image" src="https://github.com/user-attachments/assets/788f6f9f-60fb-44f4-b3e5-dff20318a105">
