### ISSUE TITLE
bug: Problem with self-join

### ISSUE THREAD

**Issue by zerodarkzone** [eakmanrq/sqlframe#212]
Hi,

I want to continue the conversation I started on https://github.com/eakmanrq/sqlframe/issues/210

I think you only solved a very especific case of the problem. When using any other operator different than an equals or when using a literal in the condition it fails.

For example:
``` Python
from sqlframe.duckdb import DuckDBSession
from sqlframe.duckdb import functions as F

session = DuckDBSession()

df_employee = session.createDataFrame(
    [
        {"id": 1, "fname": "Jack", "lname": "Shephard", "age": 37, "store_id": 1, "active": True},
        {"id": 2, "fname": "John", "lname": "Locke", "age": 65, "store_id": 2, "active": True},
        {"id": 3, "fname": "Kate", "lname": "Austen", "age": 37, "store_id": 3, "active": True},
        {"id": 4, "fname": "Claire", "lname": "Littleton", "age": 27, "store_id": 1, "active": True},
        {"id": 5, "fname": "Hugo", "lname": "Reyes", "age": 29, "store_id": 3, "active": True},
    ]
)

new_df = df_employee.where(F.col("age") > 40).select(
    F.col("id"),
    F.col("fname"),
    F.col("lname"),
    F.col("age"),
    F.col("store_id"),
    F.lit(False).alias("active"),
)

print(df_employee.join(
    new_df,
    df_employee["id"].eqNullSafe(new_df["id"]) | new_df["active"] | new_df["id"].isNull(),
).expression.sql(pretty=True))

```
Gives the following SQL.
``` sql
WITH t29415584 AS (
  SELECT
    CAST(id AS BIGINT) AS id,
    CAST(fname AS TEXT) AS fname,
    CAST(lname AS TEXT) AS lname,
    CAST(age AS BIGINT) AS age,
    CAST(store_id AS BIGINT) AS store_id,
    CAST(active AS BOOLEAN) AS active
  FROM (VALUES
    (1, 'Jack', 'Shephard', 37, 1, TRUE),
    (2, 'John', 'Locke', 65, 2, TRUE),
    (3, 'Kate', 'Austen', 37, 3, TRUE),
    (4, 'Claire', 'Littleton', 27, 1, TRUE),
    (5, 'Hugo', 'Reyes', 29, 3, TRUE)) AS a1(id, fname, lname, age, store_id, active)
), t15848639 AS (
  SELECT
    CAST(id AS BIGINT) AS id,
    CAST(fname AS TEXT) AS fname,
    CAST(lname AS TEXT) AS lname,
    CAST(age AS BIGINT) AS age,
    CAST(store_id AS BIGINT) AS store_id,
    CAST(active AS BOOLEAN) AS active
  FROM (VALUES
    (1, 'Jack', 'Shephard', 37, 1, TRUE),
    (2, 'John', 'Locke', 65, 2, TRUE),
    (3, 'Kate', 'Austen', 37, 3, TRUE),
    (4, 'Claire', 'Littleton', 27, 1, TRUE),
    (5, 'Hugo', 'Reyes', 29, 3, TRUE)) AS a1(id, fname, lname, age, store_id, active)
  WHERE
    10 = 10
), t22841635 AS (
  SELECT
    id,
    fname,
    lname,
    age,
    store_id,
    FALSE AS active
  FROM t15848639
  WHERE
    age > 40
)
SELECT
  t29415584.id,
  t29415584.fname,
  t29415584.lname,
  t29415584.age,
  t29415584.store_id,
  t29415584.active,
  t22841635.id,
  t22841635.fname,
  t22841635.lname,
  t22841635.age,
  t22841635.store_id,
  t22841635.active
FROM t29415584
INNER JOIN t22841635
  ON t29415584.id IS NOT DISTINCT FROM t29415584.id
  OR t29415584.active
  OR t29415584.id IS NULL

```

As you see, all the join conditions are using the wrong CTE.

I have a [PR](https://github.com/zerodarkzone/sqlframe/pull/2/files) on my fork which solves most of the issues but breaks your original self-join test.

**Comment by eakmanrq** [comment]
Appreciate the follow up @zerodarkzone. I see what you are doing in your fork but I'm hesitant to resolve this using a solution like that since it changes the way that `branch_id` behaves. It really is meant to help differentiate entirely different Dataframe lineages. It was introduced partially because of that test cases which as you pointed out your change breaks. 

That being said, if I had to pick between supporting the behavior in that test case vs. what you are asking for here I would favor what you are wanting. But with the end goal being emulating the PySpark API, I'm open to adding more complexity if it means I can solve both.

Check out the PR I opened. The basic idea is that since the join on expression is resolved prior to the join method being called, I need a way to figure out in a self-join which of the dataframes were used to reference the column when using the `df["col"]` syntax. Therefore I created UUIDs that I add as metadata on the column expressions whenever that syntax is used. Therefore when I hit this self-reference case I can check the known UUIDs and determine which Dataframe referenced the columns prior to being resolved and update accordingly. Not pretty but I believe resolves these known use cases while also supporting the existing test case.

Please take a look at the PR when you get a minute and let me know so I can make sure we are aligned before merging. Thanks!

**Comment by zerodarkzone** [comment]
Hi,

I was modifyng the select function to make my fix work with the test cases but I think the fix on the PR is a lot better.

I've tested it with some code I'm currently running on databricks (This is how I've found the issue) and everything is working as expected. (I'm finding a lot of less "bugs/problems" in this library than what I've found trying to use Snowpark. I think you've done a really good job)

Thanks
