### ISSUE TITLE
Problem with sqlglot version

### ISSUE THREAD

**Issue by zerodarkzone** [eakmanrq/sqlframe#225]
Hi,

Sqlglot 26 introduced a breaking change (Actually I would argue it is actually a  bug https://github.com/tobymao/sqlglot/issues/4541) when using the merge statement. I know this does not really affect the current sqlframe library but it breaks what I'm doing right now to add more DML statements (update, delete, merge).

The issue can be fixed for the newest sqlglot version but it breaks compatibility with the previous ones. I think the requirements should be tightened a little more.

**Comment by eakmanrq** [comment]
The reason why the requirements are so loose is because I want to make sure SQLFrame doesn't cause issues for users who are also using other tools that depend on SQLGlot. That being said, the compatibility range listed currently is misleading so I'm good with eventually setting the lower bound to 26. Just want to wait a bit for it to become more widely adopted before doing so. Therefore you can assume 26+ in the Table API work you are doing and will eventually enforce that restriction.

Btw looks like the bug was fixed so we can enforce >= the version with that fix once it is more widely adopted.

**Comment by zerodarkzone** [comment]
Great, then I'll keep working on it assuming sqlglot 26+.
