### ISSUE TITLE
add support for toArrow()

### ISSUE THREAD

**Issue by djouallah** [eakmanrq/sqlframe#54]
finally it was added to Spark 

https://github.com/apache/spark/pull/45481

**Comment by eakmanrq** [comment]
Nice. Looks like this will be added in 4.0.0. I will start planning for how SQLFrame will support this.

**Comment by djouallah** [comment]
gentle ping as i see you fixed already schema

**Comment by eakmanrq** [comment]
Yeah I was planning on starting to support the 4.0.0 API once it is actually released. Can you provide an example of how you want to use `toArrow` with SQLFrame? I'm assuming it is for DuckDB right?

**Comment by djouallah** [comment]
Copy data to Delta table using the python writer which accepted arrow table as input

**Comment by eakmanrq** [comment]
Would you be doing this using DuckDB? I'm not sure what you mean by python writer.

**Comment by djouallah** [comment]
Yes DuckDB

**Comment by eakmanrq** [comment]
Thanks for the details @djouallah. I do intend to do this, but just not sure on the timeline right now. I'm still trying to cover more gaps in the current DataFrame API coverage first.

**Comment by djouallah** [comment]
here is my pitch, let's early adopter have this pattern working,  raw data --- sqlframe --- arrow--- delta/iceberg and you will get the remaining gaps in the fullness of time :)

**Comment by eakmanrq** [comment]
Yeah I see your point. I'm good with allocating some time to this and see what the complexity looks like. I see the value in implementing this pattern. Going to fix some remaining issues and then start exploring this.

**Comment by eakmanrq** [comment]
Are you using the Databricks engine with SQLFrame when running in your app?

**Comment by eakmanrq** [comment]
@pblocz Making sure you see the question. I'm definitely open to adding support to more engines but I want to make sure I understand your use case first.

**Comment by pblocz** [comment]
@eakmanrq sorry, on holidays due to Easter. Yes this is the databricks engine.

My use case is to minimize the amount of data moving between databricks and the app, so I want to use sqlframes for:
- update / merge / insert, which works well as it is.
- query data doing the minimal transformations needed using sqlframes and then do the transformations needed locally using polars (for example I have a couple of visualization where I have to aggregate or pivot, but I still want to show the whole table or metrics like totals)

**Comment by eakmanrq** [comment]
No worries @pblocz  - I personally struggle with Github notifications and easily miss comments without my name. I wrote this message on my phone while between things and it came across differently then I intended. Either way I appreciate the additional info.

I opened a PR adding `toArrow` support for Databricks. The batching part required a bit of a hack due to how Databricks SQL connection implementing batching for pyarrow. Just create a new issue if you have any problems and I will follow up. Thanks!
